language: csharp
solution: Flexberry ORM.sln
install:
  - nuget restore "Flexberry ORM.sln"
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug-Net45 "Flexberry ORM.sln"
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./NewPlatform.Flexberry.ORM.Tests/bin/Debug-Net45/NewPlatform.Flexberry.ORM.Tests.dll