language: csharp
solution: Flexberry ORM.sln
install:
  - nuget restore "Flexberry ORM.sln"
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug-Net45 "Flexberry ORM.sln"
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/xunit.console.exe ./NewPlatform.Flexberry.ORM.Tests/bin/Debug-Net45/NewPlatform.Flexberry.ORM.Tests.dll