language: csharp
solution: Flexberry ORM.sln
install:
  - nuget restore "Flexberry ORM.sln"
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug-Net45 "Flexberry ORM.sln"
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe ./NewPlatform.Flexberry.ORM.Tests/bin/Debug-Net45/NewPlatform.Flexberry.ORM.Tests.dll